### ISSUE TITLE
Sharepoint Online uploading/moving/creating in a foreign language.

### ISSUE THREAD

**Issue by M4ynvs** [nextcloud/sharepoint#16]
### Steps to reproduce
1. Connect SharePoint Plugin to O365 Site Collection library (in a foreign language).
2. Head to the connected folder and try to upload, create or delete a file/folder.

### Expected behaviour
File is uploaded and appears under both SharePoint and NextCloud.

### Actual behaviour
File fails to upload, throwing error "File does not exist", only happens in foreign language document libraries, it works just fine in English sites/pages.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** Apache 2.4.18

**Database:** mysql  Ver 15.1 Distrib 10.2.13-MariaDB

**PHP version:** 7.0.28

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh installation

**Where did you install Nextcloud from:** via "Ubuntu 16.04 OVA: Pre-installed Nextcloud" VM file

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - issuetemplate: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.3
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - sharepoint: 1.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***Edited IP Address***",
            "nextcloud",
            "***Domain addr***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***Domain addr***\/",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "log_rotate_size": "10485760",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/ncdata\/nextcloud.log",
        "logtimezone": "Europe\/Helsinki",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... (whatever the default is)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... (whatever the default is)

### Client configuration
**Browser:** Chome/Firefox/Edge/Safari - latest versions

**Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
**Log from nextcloud admin logging page:**
Fatal	webdav Exception: File /sites/ *<my site collection name>*/test_nc/testingupload.txt does not exist. (The "File" and "does not exist" is in the pages language, translated it here)

    /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRequest.php - line 138: Office365\PHP\Client\Runtime\ClientRequest->validateResponse('{"error" {"code...')
    /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRuntimeContext.php - line 129: Office365\PHP\Client\Runtime\ClientRequest->executeQuery()
    /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/SharePoint/ClientContext.php - line 83: Office365\PHP\Client\Runtime\ClientRuntimeContext->executeQuery()
    /var/www/nextcloud/apps/sharepoint/lib/Client.php - line 399: Office365\PHP\Client\SharePoint\ClientContext->executeQuery()
    /var/www/nextcloud/apps/sharepoint/lib/Client.php - line 126: OCA\SharePoint\Client->loadAndExecute(Object(Office365\PHP\Client\SharePoint\File), Array)
    /var/www/nextcloud/apps/sharepoint/lib/Client.php - line 90: OCA\SharePoint\Client->fetchFile('/sites/ *<my site collection name>*/te...', Array)
    [internal function] OCA\SharePoint\Client->OCA\SharePoint\{closure}(*** sensitive parameters replaced ***)
    /var/www/nextcloud/apps/sharepoint/lib/Client.php - line 99: call_user_func_array(Object(Closure), Array)
    /var/www/nextcloud/apps/sharepoint/lib/Storage/Storage.php - line 597: OCA\SharePoint\Client->fetchFileOrFolder('/sites/ *<my site collection name>*/te...', Array)
    /var/www/nextcloud/apps/sharepoint/lib/Storage/Storage.php - line 256: OCA\SharePoint\Storage\Storage->getFileOrFolder('/sites/ *<my site collection name>*/te...')
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 224: OCA\SharePoint\Storage\Storage->file_exists('testingupload.t...')
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 244: OC\Files\Storage\Wrapper\Wrapper->file_exists('testingupload.t...')
    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 224: OC\Files\Storage\Wrapper\Availability->file_exists('testingupload.t...')
    /var/www/nextcloud/lib/private/Files/View.php - line 1322: OC\Files\Storage\Wrapper\Wrapper->file_exists('testingupload.t...')
    /var/www/nextcloud/lib/private/Files/View.php - line 1371: OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), 'testingupload.t...', 'SharePoint1/tes...')
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/ObjectTree.php - line 157: OC\Files\View->getFileInfo('/ncadmin/files/...')
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/LockPlugin.php - line 59: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('SharePoint1/tes...')
    [internal function] OCA\DAV\Connector\Sabre\LockPlugin->getLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...')
    {main}


**Log with multple actions create/upload/move in the nextcloud.log file**
# creating a sheet file via nextcloud
{"reqId":"randomID","level":3,"time":"date and time","remoteAddr":"address","user":"ncadmin","app":"index","method":"POST","url":"\/nextcloud\/index.php\/apps\/richdocuments\/ajax\/documents\/create","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Faili \\\/sites\\\/*<my site collection name>*\\\/test_nc\\\/testsheet.ods pole olemas.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRequest.php(138): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRequest->validateResponse('{\\\"error\\\":{\\\"code...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRuntimeContext.php(129): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRequest->executeQuery()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/SharePoint\\\/ClientContext.php(83): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRuntimeContext->executeQuery()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(399): Office365\\\\PHP\\\\Client\\\\SharePoint\\\\ClientContext->executeQuery()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(126): OCA\\\\SharePoint\\\\Client->loadAndExecute(Object(Office365\\\\PHP\\\\Client\\\\SharePoint\\\\File), Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(90): OCA\\\\SharePoint\\\\Client->fetchFile('\\\/sites\\\/*<my site collection name>*\\\/te...', Array)\\n#6 [internal function]: OCA\\\\SharePoint\\\\Client->OCA\\\\SharePoint\\\\{closure}(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(99): call_user_func_array(Object(Closure), Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Storage\\\/Storage.php(597): OCA\\\\SharePoint\\\\Client->fetchFileOrFolder('\\\/sites\\\/*<my site collection name>*\\\/te...', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Storage\\\/Storage.php(256): OCA\\\\SharePoint\\\\Storage\\\\Storage->getFileOrFolder('\\\/sites\\\/*<my site collection name>*\\\/te...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OCA\\\\SharePoint\\\\Storage\\\\Storage->file_exists('testsheet.ods')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(244): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('testsheet.ods')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('testsheet.ods')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1148): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('testsheet.ods')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(541): OC\\\\Files\\\\View->basicOperation('file_exists', '\\\/SharePoint1\\\/te...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(687): OC\\\\Files\\\\View->file_exists('\\\/SharePoint1\\\/te...')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/Controller\\\/DocumentController.php(336): OC\\\\Files\\\\View->file_put_contents('\\\/SharePoint1\\\/te...', 'PK\\\\x03\\\\x04\\\\x14\\\\x00\\\\x00\\\\x08\\\\x00\\\\x00\\\\xEB&\\\\xB1H\\\\x85...')\\n#17 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\DocumentController->create('application\\\/vnd...', 'testsheet.ods', '\\\/SharePoint1')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'create')\\n#20 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'create')\\n#21 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#22 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#23 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#24 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/richdocum...')\\n#25 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#26 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRequest.php\",\"Line\":185}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.1.1"}


# uploading a file via nextcloud webpage
{"reqId":"randomID","level":4,"time":"date and time","remoteAddr":"address","user":"ncadmin","app":"webdav","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/SharePoint1\/testingupload.txt","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Faili \\\/sites\\\/*<my site collection name>*\\\/test_nc\\\/testingupload.txt pole olemas.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRequest.php(138): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRequest->validateResponse('{\\\"error\\\":{\\\"code...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRuntimeContext.php(129): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRequest->executeQuery()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/SharePoint\\\/ClientContext.php(83): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRuntimeContext->executeQuery()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(399): Office365\\\\PHP\\\\Client\\\\SharePoint\\\\ClientContext->executeQuery()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(126): OCA\\\\SharePoint\\\\Client->loadAndExecute(Object(Office365\\\\PHP\\\\Client\\\\SharePoint\\\\File), Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(90): OCA\\\\SharePoint\\\\Client->fetchFile('\\\/sites\\\/*<my site collection name>*\\\/te...', Array)\\n#6 [internal function]: OCA\\\\SharePoint\\\\Client->OCA\\\\SharePoint\\\\{closure}(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(99): call_user_func_array(Object(Closure), Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Storage\\\/Storage.php(597): OCA\\\\SharePoint\\\\Client->fetchFileOrFolder('\\\/sites\\\/*<my site collection name>*\\\/te...', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Storage\\\/Storage.php(256): OCA\\\\SharePoint\\\\Storage\\\\Storage->getFileOrFolder('\\\/sites\\\/*<my site collection name>*\\\/te...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OCA\\\\SharePoint\\\\Storage\\\\Storage->file_exists('testingupload.t...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(244): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('testingupload.t...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('testingupload.t...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1322): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('testingupload.t...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1371): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'testingupload.t...', 'SharePoint1\\\/tes...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(157): OC\\\\Files\\\\View->getFileInfo('\\\/ncadmin\\\/files\\\/...')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(59): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('SharePoint1\\\/tes...')\\n#17 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\LockPlugin->getLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#20 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRequest.php\",\"Line\":185}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.1.1"}


# moving file
{"reqId":"randomID","level":4,"time":"date and time","remoteAddr":"address","user":"ncadmin","app":"webdav","method":"MOVE","url":"\/nextcloud\/remote.php\/webdav\/SharePoint1\/test_file.txt","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Faili \\\/sites\\\/*<my site collection name>*\\\/test_nc\\\/test\\\/test_file.txt pole olemas.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRequest.php(138): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRequest->validateResponse('{\\\"error\\\":{\\\"code...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRuntimeContext.php(129): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRequest->executeQuery()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/SharePoint\\\/ClientContext.php(83): Office365\\\\PHP\\\\Client\\\\Runtime\\\\ClientRuntimeContext->executeQuery()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(399): Office365\\\\PHP\\\\Client\\\\SharePoint\\\\ClientContext->executeQuery()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(126): OCA\\\\SharePoint\\\\Client->loadAndExecute(Object(Office365\\\\PHP\\\\Client\\\\SharePoint\\\\File), Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(90): OCA\\\\SharePoint\\\\Client->fetchFile('\\\/sites\\\/*<my site collection name>*\\\/te...', Array)\\n#6 [internal function]: OCA\\\\SharePoint\\\\Client->OCA\\\\SharePoint\\\\{closure}(*** sensitive parameters replaced ***)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Client.php(99): call_user_func_array(Object(Closure), Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Storage\\\/Storage.php(597): OCA\\\\SharePoint\\\\Client->fetchFileOrFolder('\\\/sites\\\/*<my site collection name>*\\\/te...', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/lib\\\/Storage\\\/Storage.php(256): OCA\\\\SharePoint\\\\Storage\\\\Storage->getFileOrFolder('\\\/sites\\\/*<my site collection name>*\\\/te...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OCA\\\\SharePoint\\\\Storage\\\\Storage->file_exists('test\\\/test_file...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(244): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('test\\\/test_file...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('test\\\/test_file...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1322): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('test\\\/test_file...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1371): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'test\\\/test_file...', 'SharePoint1\\\/tes...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(157): OC\\\\Files\\\\View->getFileInfo('\\\/ncadmin\\\/files\\\/...')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(754): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('SharePoint1\\\/tes...')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(624): Sabre\\\\DAV\\\\Server->getCopyAndMoveInfo(Object(Sabre\\\\HTTP\\\\Request))\\n#18 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/sharepoint\\\/vendor\\\/vgrem\\\/php-spo\\\/src\\\/Runtime\\\/ClientRequest.php\",\"Line\":185}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.1.1"}
```

</details>

**Comment by AlexHowser** [comment]
Also not working sp2016 on premises with german settings.. Could not test with an english site.

**Comment by warnerbryce** [comment]
Also interested about fixing this issue.

**Comment by AlexHowser** [comment]
@blizzz any update on this? Is there any direction you can point us at?

**Comment by blizzz** [comment]
@AlexHowser not really, we're just following APIs here, and they should not be language-dependent.

**Comment by blizzz** [comment]
should be fixed with latest releases
